KaaschNicolas/Awp_Bosch

App.Core/App.Core.csproj, App.Core/DataAccess/BoschContext.cs, App.Core/Helpers/PropertyHelper.cs, App.Core/Models/AuditEntry.cs, App.Core/Services/LoggingService.cs, App/App.csproj, App/App.xaml.cs, App/appsettings.json
Loging Service + AuditEntry für DB + config von Logger
=> Dev nk bos175 into master

App.Core/Migrations/20230427195318_changeToEngAddition.Designer.cs, App.Core/Migrations/20230427195318_changeToEngAddition.cs, App.Core/Models/Diagnose.cs, App.Core/Models/Pcb.cs, App.Core/Models/Transfer.cs, App.Core/Models/User.cs
Ein paar Namen waren noch auf deutsch. Hab diese angepasst & zusätzlich eine Migration erstellt
=> ChangeToEngAddition

App/Strings/de-de/Resources.resw, App/Strings/en-us/Resources.resw, App/Views/ShellPage.xaml
Verbleibort gelöscht aus "Stammdaten"-Menu gelöscht, Abteilung in PVB umbenannt im "Auswertung"-Menu
=> Updated Navigation Menu Items

.editorconfig
Reverts KaaschNicolas/Awp_Bosch#38
=> Revert "reverting .editorconfig"

.editorconfig
Reverts KaaschNicolas/Awp_Bosch#43
=> Revert "Revert "reverting .editorconfig""

App.Core/Services/Base/CrudServiceBase.cs
Fixed Bug where Error would return ResponseCode.Success
=> Bug Fix: Changed ResponseCode from Success to Error

App/App.xaml.cs
Fixed Bug where Application would crash when changing Pages fast on application startup
=> Bug Fix: Register DbContext as Transient

App.Core/Services/Interfaces/IPcbDataService.cs, App.Core/Services/Interfaces/ITransferDataService.cs, App.Core/Services/PcbDataService.cs, App.Core/Services/TransferDataService.cs, App/App.xaml.cs
CRUD-Funktionalität für Einzelansicht des PCB (alle Transfers pro Pcb)
=> Zuarbeitfues lisa

App/ViewModels/StorageLocationViewModel.cs, App/Views/StorageLocationPage.xaml, App/Views/StorageLocationPage.xaml.cs
=> Anbindung des Refresh Buttons

App/ViewModels/DiagnoseViewModel.cs, App/ViewModels/PcbTypeViewModel.cs, App/Views/DiagnosePage.xaml, App/Views/DiagnosePage.xaml.cs, App/Views/PcbTypePage.xaml, App/Views/PcbTypePage.xaml.cs
mir ist aufgefallen, dass es bei den anderen Stammdatenseite auch nicht funktioniert
=> Bos-269 Refresh Buttons on Diagnose & PcbType Page

App/ViewModels/StorageLocationViewModel.cs, App/Views/StorageLocationPage.xaml, App/Views/StorageLocationPage.xaml.cs
=> Anbindung des Refresh Buttons StorageLocation

App.Core/Services/TransferDataService.cs, App/ViewModels/CreatePcbViewModel.cs, App/ViewModels/PcbPaginationViewModel.cs, App/ViewModels/PcbSingleViewModel.cs, App/Views/PcbSinglePage.xaml, App/Views/PcbSinglePage.xaml.cs, App/Views/PcbViewPage.xaml, App/Views/PcbViewPage.xaml.cs, App/Views/ShellPage.xaml, App/Views/TransfersPage.xaml
Reverts KaaschNicolas/Awp_Bosch#71
=> Revert "Reli1017 dev"

App/ViewModels/CreatePcbViewModel.cs, App/ViewModels/UpdatePcbViewModel.cs, App/Views/CreatePcbPage.xaml, App/Views/UpdatePcbPage.xaml
CalendarDatePicker in den Erstellansicht für Leiterplatten hinzugefügt. 
MaxDate zu allen CalendarDatePicker hinzugefügt, damit man kein Datum in der Zukunft auswählen kann.
=> Added CalendarDatePicker to Create Pcb View, added MaxDate to CalendaDatePicker

App/ViewModels/PcbPaginationViewModel.cs, App/ViewModels/PcbSingleViewModel.cs, App/Views/DiagnosePage.xaml, App/Views/PcbSinglePage.xaml, App/Views/PcbSinglePage.xaml.cs, App/Views/PcbTypePage.xaml, App/Views/PcbViewPage.xaml, App/Views/PcbViewPage.xaml.cs, App/Views/StorageLocationPage.xaml, App/Views/StorageLocationsViewPage1.xaml
Fix für Issue #35 
Änderung Binding der Property "Visibility" in PcbSinglePage.xaml
=> minor changes; fix Issue #35

App.Core/Services/Base/CrudServiceBase.cs, App.Core/Services/MockDataService.cs, App.Core/Services/PcbDataService.cs, App.Core/Services/mockData/transferMockData.json
Mock Daten werden wieder korrekt geladen.
Logik hinter crudService.getAll() logisch gemacht.
=> fix mockData

App.Core/DataAccess/BoschContext.cs, App.Core/Services/AuthenticationService.cs, App.Core/Services/Interfaces/IAuthenticationService.cs, App.Core/Services/MockDataService.cs, App/Services/ActivationService.cs, App/ViewModels/CreatePcbViewModel.cs, App/ViewModels/PcbSingleViewModel.cs, App/ViewModels/TransferDialogViewModel.cs
Restructure AuthService
BOS 289 & BOS 299
SaveChangesAsync overridden
=> Dev fix startup unauth bug

App/Views/PcbViewPage.xaml
BOS 315 "Neu Laden"-Button now working
=> init bound click event

App/ViewModels/PcbSingleViewModel.cs
Code war irgendwann rausgeflogen, ist jetzt wieder drin
=> Anzeige der Umlauf-Historie und Fehler gefixt

App/ViewModels/PcbSingleViewModel.cs
bei nicht vorhandenem Fehler wird "nicht vorhanden" in Expander angezeigt
=> Fehleranzeige gefixt

App/Models/PaginatedPcb.cs
=> BOS-334 Fix Pcb Grid View

App/ViewModels/CreatePcbTypeViewModel.cs
Sachnummer Standardwert auf 1 gesetzt, da Property nicht aktualisert wird wenn NumberBox nicht verendert wird
=> BOS-335 added default value

App/ViewModels/PcbSingleViewModel.cs
Neuer Eintrag in Umlauf-Historie beinhaltet jetzt Daten
=> Update transfer history when transfer added

App.Core/Services/Base/CrudServiceBase.cs, App.Core/Services/Interfaces/ITransferDataService.cs, App.Core/Services/StorageLocationDataService.cs, App.Core/Services/TransferDataService.cs, App/App.csproj, App/App.xaml.cs, App/Helpers/PlotModelExtensions.cs, App/Services/PageService.cs, App/ViewModels/DwellTimeEvaluationViewModel.cs, App/Views/DwellTimeEvalutionPage.xaml, App/Views/DwellTimeEvalutionPage.xaml.cs, App/Views/ShellPage.xaml
Erster Plotting Durchstich, Daten noch nicht repräsentativ
=> Bos 285 into dev

App/Models/PaginatedPcb.cs, App/Views/DwellTimeEvalutionPage.xaml, App/Views/PcbViewPage.xaml, App/Views/ShellPage.xaml
Leiterplattenübersicht überarbeitet, Pagination aus Navigation entfernt, Plot in Auswertung wird angezeigt
=> aktuelle Änderungen Stand Kunden-Meeting

App/App.xaml.cs, App/Services/PageService.cs, App/Strings/en-us/Resources.resw, App/ViewModels/CreateUserViewModel.cs, App/ViewModels/UpdateUserViewModel.cs, App/ViewModels/UsersViewModel.cs, App/Views/CreateUserPage.xaml, App/Views/CreateUserPage.xaml.cs, App/Views/ShellPage.xaml, App/Views/UpdateUserPage.xaml, App/Views/UpdateUserPage.xaml.cs, App/Views/UsersPage.xaml, App/Views/UsersPage.xaml.cs
Benutzerverwaltung (ohne Rollen)
=> Benutzerverwaltung UI

App/Views/ShellPage.xaml
Stammdaten-Submenu öffnet sich wieder
=> fixed menu bug

App.Core/DataAccess/BoschContext.cs, App.Core/Validator/AuditEntryValidator.cs, App.Core/Validator/CommentValidator.cs, App.Core/Validator/DeviceValidator.cs, App.Core/Validator/DiagnoseValidator.cs, App.Core/Validator/ErrorTypeValidator.cs, App.Core/Validator/PcbTypeValidator.cs, App.Core/Validator/PcbValidator.cs, App.Core/Validator/StorageLocationValidator.cs, App.Core/Validator/TransferValidator.cs, App/Activation/DefaultActivationHandler.cs, App/Strings/de-de/Resources.resw, App/Strings/en-us/Resources.resw
Kommentare hinzugefügt zu den Validatoren & dem DataAccess.
Name der Anwendung zu Kreisler abgeändert und das Dashboard als Startbildschirm  der Applikation festgelegt
=> Titel & commentary

App/Views/ShellPage.xaml
=> Bos 359 into dev  

App.Core/DTOs/EvaluationDTO.cs, App.Core/DTOs/EvaluationPcbTypeI_ODTO.cs, App.Core/DataAccess/BoschContext.cs, App.Core/Services/Interfaces/IPcbTypeEvaluationService.cs, App.Core/Services/PcbTypeEvaluationService.cs, App/App.xaml.cs, App/Services/PageService.cs, App/Strings/en-us/Resources.resw, App/ViewModels/PcbTypeI_OEvaluationViewModel.cs, App/Views/DwellTimeEvalutionPage.xaml, App/Views/PcbTypeI_OEvaluationPage.xaml, App/Views/PcbTypeI_OEvaluationPage.xaml.cs, App/Views/ShellPage.xaml
Auswertungsseite für Ein- & Ausgänge der Sachnummern
=> Bos 62 Auswertung Ein/Ausgaenge

App.Core/Models/Enums/Role.cs, App/Helpers/AuthServiceHelper.cs, App/ViewModels/PcbSingleViewModel.cs, App/Views/DashboardPage.xaml, App/Views/DwellTimeEvalutionPage.xaml, App/Views/PcbSinglePage.xaml, App/Views/PcbSinglePage.xaml.cs, App/Views/PcbTypeEvaluationPage.xaml, App/Views/PcbTypeI_OEvaluationPage.xaml, App/Views/PcbViewPage.xaml, App/Views/PcbViewPage.xaml.cs, App/Views/ShellPage.xaml
Schichtleitung zu StandardUser geändert -> DB überprüfen, ob "Schichtleitung" irgendwo drin steht und abändern, sonst startet die Anwendung nicht
Beschränkungen zu LP-Übersicht, Detailansicht, User-Verwaltung & Stammdaten hinzugefügt
Code aufgeräumt
=> Auth Rollen zuweisen
